- hosts: dev
  become: true
  tasks: 
  - name : copy mulyiple files using var 
    copy:
      src: "{{item.source}}"
      dest: "{{item.dest}}"
    with_items:
      - {"source": "ab","dest": "/opt/ab"}

